---
- name: Provision Packer VM
  hosts: all
  become: yes
  
  vars:
      vm_system_type: "{{ lookup('env', 'VM_SYSTEM_TYPE') }}"
      ca_cert: "{{ lookup('env', 'CA_CERT') }}"

  tasks:
    - name: Add CA certificate
      include_tasks: "playbook/certificate-ca.yml"

    - name: Disable IPV6
      include_tasks: "playbook/ipv6-disable.yml"

    - name: Config Hot CPU and Memory
      include_tasks: "playbook/hot-cpu-memory.yml"

    - name: Config Cloud Init
      include_tasks: "playbook/cloud-init.yml"

    - name: Clean TPL
      include_tasks: "playbook/clean-tpl.yml"